export { default as BatterySection } from "./BatterySection";
export { default as CameraSection } from "./CameraSection";
export { default as ColorSection } from "./ColorSection";
export { default as DesignSection } from "./DesignSection";
export { default as DisplaySection } from "./DisplaySection";
export { default as HeroSection } from "./HeroSection";
export { default as PhoneModel } from "./PhoneModel";
export { default as ProcessorSection } from "./ProcessorSection";
export { default as Quote } from "./Quote";
